language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install
  - echo "error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/atoum -d Tests/ -bf Tests/bootstrap.php
